---

- name: Archive {{ image_name }}
  docker_image:
    name: "{{ image_name.split(':')[0] }}"
    tag: "{{ image_name.split(':')[1] }}"
    archive_path: "{{ mirror_base }}/images/infrastructure/{{ image_name | replace('/','-') | replace(':','_') }}.tar"
    source: pull

#- name: Remove Image from local images
#  podman_image:
#    name: '{{ image_repo }}/{{ image_name }}'
#    tag: '{{ image_tag }}'
#    state: absent
#  when: ( cleanup_local_podman | bool )
