---

- name: Create directory for image archives
  file:
    path: '{{ mirror_base }}/ocp-{{ ocp_ver }}/images/infrastructure'
    state: directory

# Podman_image doesn't work well
#- name: Create Image Archives
#  include_tasks: archive_image.yml

- name: Ensure podman is installed
  become: true
  package:
    name: podman
    state: present
  when: ( podman | bool )

- name: Install docker
  become: true
  package:
    name: docker-ce
    state: present
  when: ( docker | bool )

- name: Ensure docker daemon is running
  become: true
  service:
    name: docker
    state: started
  when: ( docker | bool )

- name: Install required pip modules for docker
  pip:
    name: 'docker'
    state: present
    executable: '{{ pip_cmd }}'
    extra_args: --user
  when: ( docker | bool )

- name: Create Image Archives
  include_tasks: docker_archive_image.yml
  vars:
    image_name: '{{ item }}'
  with_items:
    - '{{ cluster_images }}'
    - '{{ optional_images }}'
    - '{{ additional_images }}'
